language: generic

os: linux-ppc64le

install:

 - ./ci_support/install.sh

 # Build conda package
 - cd powerai/conda-recipes/zip-feedstock
 - conda build .

script:
# Upload built conda package to UNICAMP FTP
 - ls $HOME/miniconda/conda-bld/linux-ppc64le/*.tar.bz2
 - 'if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then ./ci_support/ftp_upload.sh # Upload build_artifacts to UNICAMP FTP